### ISSUE TITLE
表格Bug 对 列 进行合并单元格后，对之后行点击呼唤不出列气泡框

### ISSUE THREAD

**Issue by xiangshu233** [Seedsa/echo-editor#3]
请看演示
选中位置似乎也不对了
https://github.com/Seedsa/echo-editor/assets/49575330/db3c3b3c-9901-44bb-a30b-7f813d9acc32

**Comment by xiangshu233** [comment]
表格还有一个bug，设置 10 * 10 表格后表格内容超出编辑器出现滚动条，应该是 `min-width` 导致的

**Comment by Seedsa** [comment]
官方模板的表格也有同样的问题，后续可能会重构表格拓展。
