### ISSUE TITLE
How to hide list EMBED 

### ISSUE THREAD

**Issue by gamedevgs** [Seedsa/echo-editor#5]
hi i tried to integrate into my nuxt3 product. but now there are some problems. i want to ask how to hide these EMBED icons. thanks
![image](https://github.com/user-attachments/assets/15a1d487-63fd-4a79-b571-9fef4fd193ac)

**Comment by Seedsa** [comment]
BaseKit.configure({
    iframe: false
  })

**Comment by gamedevgs** [comment]
thansk so much

**Comment by vishnuasalta** [comment]
this iframe option is not working, even tried in SlashCommand.configure that too not works, Can help ?
