### ISSUE TITLE
[ERR CSS]css style syntax conflicts with bootstrap style if integrated separately into the project in use.

### ISSUE THREAD

**Issue by gamedevgs** [Seedsa/echo-editor#6]
hello. maybe i'm still here to test and report bugs for the product, after adding more editors the css tag names conflict with some previous css tag names. i see in the original syntax of css is scss but it seems it is not completely scss syntax 100%. so it caused the above errors. if anyone has encountered similar problems can discuss how to fix the error here.
![image](https://github.com/user-attachments/assets/0e96ad68-d610-4fce-aa10-bda30343519e)

**Comment by Seedsa** [comment]
check out [this](https://stackoverflow.com/questions/62688037/can-use-both-tailwind-css-and-bootstrap-4-at-the-same-time)
