### ISSUE TITLE
行内代码的字体大小无法设置

### ISSUE THREAD

**Issue by dhx291** [Seedsa/echo-editor#7]
如图，行内代码的字体无法随其他文字一样变化：
![image](https://github.com/user-attachments/assets/f809418c-3bef-4a24-a5c5-598e537920eb)

**Comment by Seedsa** [comment]
tiptap默认不支持代码标记中使用其他标记，但你可以通过扩展这个扩展来改变这一点
`Code.extend({ excludes: null })`
https://github.com/ueberdosis/tiptap/issues/2563
